// lib/services/export_service.dart
import 'dart:io';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';
import '../models/saved_job.dart';
import '../services/calculator_engine.dart';

final _fmt = NumberFormat('#,##0.00');
final _fmt4 = NumberFormat('#,##0.0000');

class ExportService {
  final CalculatorEngine engine;
  ExportService(this.engine);

  Future<void> exportToPdf(SavedJob job) async {
    final pdf = pw.Document();
    final result = engine.calculate(
      product: _parseProduct(job.productType),
      l: job.l,
      w: job.w,
      g: job.g,
      qty: job.qty,
      numLayers: job.numLayers,
      layers: [job.layer1, job.layer2, job.layer3, job.layer4],
    );

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(30),
        build: (ctx) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('Ci™ Metering | Vacuum Bags SARL',
                    style: pw.TextStyle(
                        fontSize: 20, fontWeight: pw.FontWeight.bold)),
                pw.Text(DateFormat('dd/MM/yyyy').format(DateTime.now()),
                    style: const pw.TextStyle(fontSize: 11)),
              ],
            ),
            pw.Divider(thickness: 1.5),
            pw.SizedBox(height: 8),
            pw.Text('METERING REPORT',
                style: pw.TextStyle(
                    fontSize: 14, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 8),
            _pdfInfoRow('Job', job.jobName),
            if (job.customerName != null)
              _pdfInfoRow('Customer', job.customerName!),
            if (job.itemCode != null) _pdfInfoRow('Item Code', job.itemCode!),
            _pdfInfoRow('Product', job.productType),
            _pdfInfoRow('Dimensions',
                'L=${job.l} cm  W=${job.w} cm  G=${job.g} cm'),
            _pdfInfoRow('Quantity', '${_fmt.format(job.qty)} pcs'),
            _pdfInfoRow('Layers', '${job.numLayers}'),
            pw.SizedBox(height: 12),
            // Layers table
            pw.Table.fromTextArray(
              headers: ['Structure', 'WEIGHT/KG', 'WEIGHT/UNIT gr', 'METERS/QTY', 'METERS/KG'],
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9),
              cellStyle: const pw.TextStyle(fontSize: 9),
              data: _buildPdfRows(job, result),
            ),
            if (job.note != null && job.note!.isNotEmpty) ...[
              pw.SizedBox(height: 12),
              pw.Text('Note: ${job.note}',
                  style: const pw.TextStyle(fontSize: 10)),
            ],
            pw.Spacer(),
            pw.Divider(),
            pw.Text('Generated by Ci™ Metering v2.1 — Vacuum Bags SARL (vacuumbags.com.lb) | Powered by CCG (ccg.support)',
                style: const pw.TextStyle(fontSize: 8)),
          ],
        ),
      ),
    );

    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/${job.jobName}_metering.pdf');
    await file.writeAsBytes(await pdf.save());
    await Share.shareXFiles([XFile(file.path)], text: 'Metering Report: ${job.jobName}');
  }

  Future<void> exportToCsv(SavedJob job) async {
    final result = engine.calculate(
      product: _parseProduct(job.productType),
      l: job.l,
      w: job.w,
      g: job.g,
      qty: job.qty,
      numLayers: job.numLayers,
      layers: [job.layer1, job.layer2, job.layer3, job.layer4],
    );

    final buf = StringBuffer();
    buf.writeln('Ci™ Metering Report — Vacuum Bags SARL (vacuumbags.com.lb) | Powered by CCG (ccg.support)');
    buf.writeln('Job,${job.jobName}');
    buf.writeln('Date,${DateFormat('dd/MM/yyyy').format(DateTime.now())}');
    if (job.customerName != null) buf.writeln('Customer,${job.customerName}');
    if (job.itemCode != null) buf.writeln('Item Code,${job.itemCode}');
    buf.writeln('Product,${job.productType}');
    buf.writeln('L (cm),${job.l}');
    buf.writeln('W (cm),${job.w}');
    buf.writeln('G (cm),${job.g}');
    buf.writeln('Qty,${job.qty}');
    buf.writeln('Layers,${job.numLayers}');
    buf.writeln();
    buf.writeln('Structure,WEIGHT/KG,WEIGHT/UNIT gr,METERS/QTY,METERS/KG');

    final structs = [
      ('1 Layer (${job.layer1})', result.layer1Result),
      if (job.numLayers >= 2)
        ('2 Layers (${job.layer1}/${job.layer2})', result.layer2Result),
      if (job.numLayers >= 3)
        ('3 Layers', result.layer3Result),
      if (job.numLayers >= 4)
        ('4 Layers', result.layer4Result),
    ];
    for (final (label, r) in structs) {
      if (r != null) {
        buf.writeln(
            '$label,${r.weightKg.toStringAsFixed(3)},${r.weightUnitGr.toStringAsFixed(4)},${r.metersQty.toStringAsFixed(2)},${r.metersKg.toStringAsFixed(2)}');
      }
    }

    if (job.note != null) buf.writeln('\nNote,${job.note}');

    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/${job.jobName}_metering.csv');
    await file.writeAsString(buf.toString());
    await Share.shareXFiles([XFile(file.path)], text: 'Metering CSV: ${job.jobName}');
  }

  List<List<String>> _buildPdfRows(SavedJob job, MeteringResult result) {
    final rows = <List<String>>[];
    final structs = [
      ('1L: ${job.layer1}', result.layer1Result),
      if (job.numLayers >= 2)
        ('2L: ${job.layer1}/${job.layer2}', result.layer2Result),
      if (job.numLayers >= 3)
        ('3L: .../${job.layer3}', result.layer3Result),
      if (job.numLayers >= 4)
        ('4L: .../${job.layer4}', result.layer4Result),
    ];
    for (final (label, r) in structs) {
      if (r != null) {
        rows.add([
          label,
          _fmt.format(r.weightKg),
          _fmt4.format(r.weightUnitGr),
          _fmt.format(r.metersQty),
          _fmt.format(r.metersKg),
        ]);
      }
    }
    return rows;
  }

  pw.Widget _pdfInfoRow(String label, String value) => pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 3),
        child: pw.Row(children: [
          pw.SizedBox(
              width: 100,
              child: pw.Text(label,
                  style: pw.TextStyle(
                      fontWeight: pw.FontWeight.bold, fontSize: 10))),
          pw.Text(value, style: const pw.TextStyle(fontSize: 10)),
        ]),
      );

  ProductType _parseProduct(String name) {
    return ProductType.values.firstWhere(
      (p) => p.displayName == name,
      orElse: () => ProductType.zipperBag,
    );
  }
}
